name: Waka Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に更新
    - cron: "0 12 * * *"  # 毎日12時に更新
    - cron: "0 18 * * *"  # 毎日18時に更新
    - cron: "0 6 * * *"   # 毎日6時に更新
  workflow_dispatch:     # 手動実行も可能

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
